### ISSUE TITLE
Add execute permission on Unix

### ISSUE THREAD

**Issue by sytolk** [suisei-cn/actions-download-file#3]
Can we add option for execute permissions on donloaded file:
`chmod +x donwloaded_file`

**Comment by outloudvi** [comment]
Personally I think it would be good to [keep it simple, stupid](https://en.wikipedia.org/wiki/KISS_principle). For your need, maybe it's better to do it in a seperate command. For example:

```
- name: Make the file executable
  run: chmod +x filename
```

**Comment by sytolk** [comment]
ok thanks
