### ISSUE TITLE
The link to the example in README.md does not work 

### ISSUE THREAD

**Issue by r3econ** [suisei-cn/actions-download-file#4]
When I click on the link in the README.md (https://github.com/suisei-cn/starbuttons/blob/master/.github/workflows/auto_pr.yml) it gives me a 404 error.

**Comment by pzhlkj6612** [comment]
Hi. It seems that the maintainer switched the default branch of that repository. Try this: https://github.com/suisei-cn/starbuttons/blob/6745c3081dbf626e545983140187df55caa54e1e/.github/workflows/auto_pr.yml#L16-L22

**Comment by outloudvi** [comment]
The link by reply #1 is a working example. Bybthe way, the one used in production has actually been moved here now: https://github.com/suisei-cn/sbtn-assets/blob/master/.github/workflows/auto_pr.yml

I'll update the README.md later. Thanks for your message!
